config/routes.rb
Magasinsreunion::Application.routes.draw do
  
  get "listgeojson" => "pages#listgeojson"
  get "about" => "pages#about"  
  resources :stores

  devise_for :users, except: :new_user_registration
  root "pages#home"

end

app/models/location.rb
class Location < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://placehold.it/100x100" 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	if params[:city].present? && params[:activity].present?

	  	if params[:city] == "all" && params[:activity] == "all"
	  		@stores = Store.all.order('created_at DESC')
	  	elsif params[:city] == "all" && params[:activity] != "all"
	  		@stores = Store.all.order('created_at DESC').where('activity ILIKE ?', '%'+params[:activity]+'%')
	  	elsif params[:city] != "all" && params[:activity] == "all"
	  		@stores = Store.all.order('created_at DESC').where('town ILIKE ?', '%'+params[:city]+'%')
	  	else
	  		@stores = Store.all.order('created_at DESC').where('town ILIKE ? AND activity ILIKE ?', 
	  				'%'+params[:city]+'%', '%'+params[:activity]+'%')
	  	end
	else
		@stores = Store.all.order('created_at DESC')
	end
  end

  def about
  end

  def listgeojson
  	if params[:city].present? && params[:activity].present?

	  	if params[:city] == "all" && params[:activity] == "all"
	  		@stores = Store.all.order('created_at DESC')
	  	elsif params[:city] == "all" && params[:activity] != "all"
	  		@stores = Store.all.order('created_at DESC').where('activity ILIKE ?', '%'+params[:activity]+'%')
	  	elsif params[:city] != "all" && params[:activity] == "all"
	  		@stores = Store.all.order('created_at DESC').where('town ILIKE ?', '%'+params[:city]+'%')
	  	else
	  		@stores = Store.all.order('created_at DESC').where('town ILIKE ? AND activity ILIKE ?', 
	  				'%'+params[:city]+'%', '%'+params[:activity]+'%')
	  	end
	else
		@stores = Store.all.order('created_at DESC')
	end
  	
  	@featureCollection = { 
		"type" => "FeatureCollection", 
		"features" => []
	}

  	@stores.each do |store|
  		@featureCollection["features"].push({
	    	"type" => "Feature",
	    	"debug" => store.address+" "+store.postcode+" "+store.town+" Réunion",
	    	"geometry" => {
	      		"type" => "Point",
	      		"coordinates" => Geocoder.coordinates(store.address+" "+store.postcode+" "+store.town+" Réunion")
	    	},
	    	"properties" => {
	      		"title" => store.name,
	      		"description" => "<p>"+store.address+" "+store.postcode+" "+store.town+"</p><p>"+store.activity+"</p>",
	      		"marker-color" => "#e74c3c",
	      		"marker-size" => "large"
	    	}
		})
  	end

  	respond_to do |format|
	  format.html
	  format.xml  { render :xml => @featureCollection }
	  format.json { render :json => @featureCollection }
	end
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'La magasin a bien été inscrit.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Les informations ont bien été modifié.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :logo, :address, :postcode, :town, :phonenumber, :email, :name_shopper, :activity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-primary navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("http://s3.amazonaws.com/magasinsreunion/img/logo-magasinsreunion.png", alt: "Logo MagasinsReunion.re"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <h1 class="nav-title">L'annuaire de vos magasins de La Réunion </h1>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="subscription-link">
          <%= link_to "https://docs.google.com/forms/d/11NA8GXC6sJdcRDeTMnsm7fA0HT3oDKlxLJlFNWOKX_M/viewform" do %>
            
            Inscrire son magasin <span class='label label-success'>gratuit</span>
          
          <% end %>
        </li>
        <li><%= link_to "A propos", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<nav class="searchbar navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <span class="navbar-brand">Recherche</span>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= form_tag root_path, method: "get" do %>
        <ul class="nav navbar-nav">
          <li>
            <div class="form-group">
              <label for="place">Lieu </label>
              <%= select_tag(:city, options_for_select([
                  ["Sur toute l'île", "all"], 
                  ["Les Avirons", "les avirons"],
                  ["Bras-Panon", "bras-panon"],
                  ["Cilaos", "cilaos"],
                  ["Entre-Deux", "entre-deux"],
                  ["L'Etang-Salé", "etang-sale"],
                  ["Petite-Ile", "petite-ile"],
                  ["La Plaine-des-Palmistes", "plaine-des-palmistes"],
                  ["Le Port", "port"],
                  ["La Possession", "possession"],
                  ["Saint-André", "saint-andre"],
                  ["Saint-Benoît", "saint-benoit"],
                  ["Saint-Denis", "saint-denis"],
                  ["Sainte-Marie", "sainte-marie"],
                  ["Sainte-Rose", "sainte-rose"],
                  ["Sainte-Suzanne", "sainte-suzanne"],
                  ["Saint-Joseph", "saint-joseph"],
                  ["Saint-Leu", "saint-leu"],
                  ["Saint-Louis", "saint-louis"],
                  ["Saint-Paul", "saint-paul"],
                  ["Saint-Philippe", "saint-philippe"],
                  ["Saint-Pierre", "saint-pierre"],
                  ["Salazie", "salazie"],
                  ["Le Tampon", "tampon"],
                  ["Trois-Bassins", "trois-bassins"]
                ], "all"), class: "form-control") %>
            </div>
          </li>
          <li>
            <div class="form-group">
              <label for="activity">Activité </label>
              <%= select_tag(:activity, options_for_select([
                  ["Tout secteur d'activité", "all"],
                  ["Animaux", "animaux"],
                  ["Antiquités", "antiquite"],
                  ["Art", "art"],
                  ["Articles et Equipements de bureaux", "bureaux"],
                  ["Artisans", "artisans"],
                  ["Auto", "auto"],
                  ["Bazar, droguerie, quincaillerie", "bazar"],
                  ["Bijoux et Accessoires", "bijoux"],
                  ["Bricolage", "bricolage"],
                  ["Cadeaux", "cadeaux"],
                  ["Caviste", "caviste"],
                  ["Chaussures", "chaussures"],
                  ["Culture", "culture"],
                  ["Décoration", "decoration"],
                  ["Diététique et Produits bio", "dietetique"],
                  ["Electro-ménager", "electro menager"],
                  ["Epicerie fine", "epicerie"],
                  ["Fleurs et Jardins", "fleurs"],
                  ["Hifi", "hifi"],
                  ["Informatique et Multimédia", "informatique"],
                  ["Jeux vidéo", "jeux"],
                  ["Jouets", "jouets"],
                  ["Meubles", "meubles"],
                  ["Mode", "mode"],
                  ["Moto", "moto"],
                  ["Musique", "musique"],
                  ["Photo et Vidéo", "photo"],
                  ["Sport", "sport"],
                  ["Téléphonie", "telephonie"],
                  ["Tourisme", "tourisme"]
                ], "all"), class: "form-control") %>
            </div>
          </li>
          <li class="search-action search-action-text">
            <%= button_tag type: "submit" do%>
                <span class="glyphicon glyphicon-search"></span> Lancer la recherche
            <% end %>
          </li>
          <li class="search-action search-action-icon">
            <%= button_tag type: "submit" do%>
                <span class="glyphicon glyphicon-search"></span>
            <% end %>
          </li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="description" content="MagasinsReunion.re souhaite référencer la majorité des magasins de la Réunion afin d'aider les Réunionnais à trouver rapidement ce qu'ils recherchent en ligne.">
  <title>MagasinsReunion.re, le site annuaire des magasins de La Réunion</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src='https://api.tiles.mapbox.com/mapbox.js/v1.6.1/mapbox.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox.js/v1.6.1/mapbox.css' rel='stylesheet' />
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43845714-2', 'magasinsreunion.re');
  ga('send', 'pageview');

</script>
</head>
<body>

  <%= render "layouts/header" %>
  <div class="wrap container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </div>

	<footer>
		© 2014 MagasinsReunion.re
	</footer>

</body>
</html>

app/views/pages/about.html.erb
<div id="about">
	<h1>
		MagasinsReunion.re, le premier site annuaire local dédié aux commerçants physiques de La Réunion !
	</h1>
	<div class="about-content">
		<p>
			La start-up réunionnaise <%= link_to "Fing Offers", "http://fingoffers.com" %> a édité cette première solution pour les commerçants réunionnais afin de les aider à être plus proche des consommateurs de demain.
		</p>
		<p>
			<strong>Nous pensons qu’il est indispensable aujourd’hui, pour un magasin physique, d’être présent sur Internet.</strong> L’idée est de permettre aux Réunionnais de trouver rapidement en ligne les commerçants en fonction de leur localisation et de leurs secteurs d'activité. Ils pourront également accéder aux informations pratiques (adresse, téléphone, horaires d’ouverture et de fermeture et bien d’autres).
		</p>
		<p>
			<strong>Cet annuaire est dédié aux commerçants situés en ville de La Réunion.</strong>
		</p>
		<p>
			Si vous avez un ou plusieurs magasins, n'hésitez pas à vous <%= link_to "inscrire", "https://docs.google.com/forms/d/11NA8GXC6sJdcRDeTMnsm7fA0HT3oDKlxLJlFNWOKX_M/viewform"%>. Pour rappel, <strong>l'inscription à l'annuaire est totalement gratuite</strong>.
		</p>
	</div>
</div>

app/views/pages/home.html.erb
<div id="home">
	<div id="map" class="map"></div>

	<aside class="retails">

		<% if !@stores.empty? %>

		<% @stores.each do |store| %>

		<%= link_to store, class: "wrap-link" do %>

		<section data-title="<%= store.name %>" class="retail panel panel-default">
			<div class="panel-body clearfix">
				<div class="logo">
					<!-- <div class="label label-success">Ouvert</div> -->
					<%= image_tag store.logo.url(:thumb) %>
				</div>
				<div class="information">
					<h2>
						<%= store.name %>
					</h2>	
					<p>
						<%= store.address %> <br>
						<%= store.postcode %> <%= store.town %> 
					</p>
					<p>
						<%= store.phonenumber %>
					</p>
					<p>
					</p>
				</div>
			</div>
			<div class="panel-footer">
				<% 
					@activities = store.activity.split(',');

					@activities.each do |activity|
				%>
				<span class="label label-default"><strong><%= activity %></strong></span>
				<% end %>
			</div>
		</section>

		<% end %>

		<% end %>
		<% else %>
			<div class="empty-stores">
				<h3>
					Aucun magasin inscrit dans cette ville et avec l'activité indiqué... 
				</h3>
				<p>
					N'hésitez pas à effectuer une nouvelle recherche.
				</p>
			</div>
		<% end %>
	</aside>

	<script>

		var map = L.mapbox.map('map', 'julien-c.map-crig5ksu');

		map.fitBounds([
		    [-21.5, 56], 
		    [-20.7, 55.7]
		], {
		    paddingTopLeft: [450, 0]
		});

		map.setZoom(10);
		map.scrollWheelZoom.disable();
		map.zoomControl.setPosition('topright');

		pathArray = window.location.href.split( '/' );
		protocol = pathArray[0];
		host = pathArray[2];
		baseUrl = protocol + '://' + host;

		$.getJSON("/listgeojson.json" + window.location.search, function (data){
			
			for (var i = data.features.length - 1; i >= 0; i--) {
				
				if(data.features[i].geometry.coordinates !== null)
					data.features[i].geometry.coordinates.reverse();

			};

			map.featureLayer.setGeoJSON(data.features);

		});

		map.featureLayer.on('ready', function(e) {

		    $('.retail').on('mouseenter', function(){
		    	var retail = $(this);

		    	map.featureLayer.eachLayer(function(marker) {
			        if (marker.feature.properties.title === retail.data('title')) {
			            marker.openPopup();
			            
			            map.fitBounds([
						    [marker._latlng['lat'], marker._latlng['lng']-0.02]
						], {
						    paddingTopLeft: [450, 0]
						}).setZoom(14);
			        }
			    });
		    });
		});

		map.featureLayer.on('mouseover', function(e) {
		    e.layer.openPopup();
		});
		map.featureLayer.on('mouseout', function(e) {
		    e.layer.closePopup();
		});

	</script>
</div>

app/views/pages/listgeojson.html.erb
<p>
	<%= @location %>
</p>

app/views/stores/_form.html.erb
<%= form_for @store, html: {multipart: true} do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Nom du magasin" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :logo, "Logo du magasin" %><br>
    <%= f.file_field :logo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address, "Adresse" %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :postcode, "Code Postal" %><br>
    <%= f.text_field :postcode, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :town, "Ville" %><br>
    <%= f.text_field :town, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phonenumber, "Téléphone" %><br>
    <%= f.text_field :phonenumber, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email, "Email" %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :name_shopper, "Nom du gérant" %><br>
    <%= f.text_field :name_shopper, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :activity, "Activité" %><br>
    <%= f.text_field :activity, class: "form-control" %>
  </div>
  <div class="actions form-group">
    <% if current_page?(action: "new")%>
    <%= f.submit class: "btn btn-primary btn-lg", value: "Inscrire le magasin" %>
    <% else %>
    <%= f.submit class: "btn btn-primary btn-lg", value: "Modifier les informations" %>
    <% end %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Voir', @store %> |
<%= link_to 'Retour', stores_path %>

app/views/stores/index.html.erb
<h1>Liste des magasins inscrits (<%= @stores.length %>)</h1>

<%= link_to 'Ajouter un magasin', new_store_path, class: "btn btn-primary" %>

<table class="list-stores table table-bordered">
  <thead>
    <tr>
      <th>Logo</th>
      <th>Nom du magasin</th>
      <th width="10%">Ville</th>
      <th width="10%">Téléphone</th>
      <th>Email</th>
      <th>Nom du gérant</th>
      <th>Activité(s)</th>
      <th width="17%">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= image_tag store.logo.url(:thumb) %></td>
        <td><%= store.name %></td>
        <td><%= store.town %></td>
        <td><%= store.phonenumber %></td>
        <td><%= store.email %></td>
        <td><%= store.name_shopper %></td>
        <td><%= store.activity %></td>
        <td>
          <%= link_to 'Voir', store %> -
          <%= link_to 'Modifier', edit_store_path(store) %> -
          <%= link_to 'Supprimer', store, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stores/new.html.erb
<h1>Ajouter un magasin</h1>

<%= render 'form' %>

<%= link_to 'Retour', stores_path %>

app/views/stores/show.html.erb
<div class="retail-show panel panel-default">
  
  <div class="panel-heading">
    <h2>
     <%= @store.name %>
    </h2>
  </div>

  <div class="panel-body clearfix">
    <div class="logo pull-left">
      <p>
        <%= image_tag @store.logo.url(:medium) %>
      </p>
    </div>
    <div class="information pull-left">
      <p class="address">
        <%= @store.address+", "+@store.postcode+" "+@store.town %>
      </p>

      <p>
        <strong>Téléphone :</strong>
        <%= @store.phonenumber %>
      </p>

      <% if user_signed_in? %>
        <p>
          <strong>Email :</strong>
          <%= @store.email %>
        </p>

        <p>
          <strong>Nom du gérant :</strong>
          <%= @store.name_shopper %>
        </p>
      <% end %>

      <p>
        <strong>Activité :</strong>
        <%= @store.activity %>
      </p>
    </div>
  </div>
  
  <% if user_signed_in? %>
    <div class="panel-footer">
      <%= link_to 'Modifier', edit_store_path(@store) %> |
      <%= link_to 'Retour', stores_path %>
    </div>
  <% else %>
    <div class="panel-footer">
      <%=link_to 'Retour', root_path %>
    </div>
  <% end %>

</div>